[libtasn1]  Update to version 4.18. Fixes JB#57060
sailfishos/libtasn1 pull request #1
Opened 2022-03-10 05:26 UTC by Thaodan

2022-03-10 05:32 UTC, vigejolla commented
The submodule still points to gitlab.com instead of our mirror

2022-03-14 08:59 UTC, saukko commented on rpm/libtasn1.spec
>  Group:      System/Libraries
Extra points cutting out groups.

2022-03-16 08:36 UTC, Tomin1 requested changes
Some changes needed.

2022-03-16 08:36 UTC, Tomin1 commented on rpm/libtasn1.spec
>  Requires(post): /sbin/install-info
These install-info dependencies in devel package are a leftover from the past. They should be removed, I think.

2022-03-16 08:36 UTC, Tomin1 commented on rpm/libtasn1.spec
>  %setup -q -n %{name}-%{version}/%{name}
You probably should change this to use %autosetup. Now the patches are not applied because there is no %patch macros.

2022-03-16 10:35 UTC, Thaodan commented
Adjusted

2022-03-16 11:28 UTC, Tomin1 requested changes

2022-03-16 11:28 UTC, Tomin1 commented on rpm/libtasn1.spec
> -Requires(post): /sbin/install-info
You removed these from doc and not from devel, like I said.

2022-03-16 13:09 UTC, Tomin1 commented
This seems to require libtool (`libtoolize`) to build. It didn't build after `sfdk build-requires reset`.

Also %check faild at "FAIL: reproducers" (after I had installed libtool to target snapshot).

2022-03-16 13:14 UTC, Thaodan commented
> This seems to require libtool (`libtoolize`) to build. It didn't build after `sfdk build-requires reset`.
> 
> Also %check failed at "FAIL: reproducers" (after I had installed libtool to target snapshot).

That's because the package version isn't matching without tag (check log).

2022-03-16 13:23 UTC, Tomin1 commented
> > This seems to require libtool (`libtoolize`) to build. It didn't build after `sfdk build-requires reset`.
> 
> Fixed.
> 
> > Also %check failed at "FAIL: reproducers" (after I had installed libtool to target snapshot).
> 
> That's because the package version isn't matching without tag (check log).

Ah, okay. So, what I actually needed is `-c no-fix-version`. :+1:

2022-03-16 13:25 UTC, Tomin1 approved these changes

2022-03-16 13:41 UTC, martyone commented
> > > Also %check failed at "FAIL: reproducers" (after I had installed libtool to target snapshot).
> > That's because the package version isn't matching without tag (check log).
> Ah, okay. So, what I actually needed is `-c no-fix-version`. +1

From a brief check I would expect that this is addressed by https://github.com/sailfishos/libtasn1/blob/e439b365467a923441b190bb1fa3f0bfafb5d1b2/rpm/libtasn1.spec#L65 - maybe something more could be done here.

2022-03-16 13:44 UTC, Tomin1 commented
> > > > Also %check failed at "FAIL: reproducers" (after I had installed libtool to target snapshot).
> > > 
> > > 
> > > That's because the package version isn't matching without tag (check log).
> > 
> > 
> > Ah, okay. So, what I actually needed is `-c no-fix-version`. +1
> 
> From a brief check I would expect that this is addressed by
> 
> https://github.com/sailfishos/libtasn1/blob/e439b365467a923441b190bb1fa3f0bfafb5d1b2/rpm/libtasn1.spec#L65
> - maybe something more could be done here.

As I understand it, the issue was that when I didn't have a tag, it used `4.13+git2+something` as the version so I ended up with `4.13` in `.tarball-version` which didn't pass the test. When I used `no-fix-version`, then I get the version in spec file and that passes the test. I should get the same result by tagging the commit I'm building, right?

2022-03-16 14:17 UTC, martyone commented
You are right. Having to tag everything you want to build would be very inconvenient. Use of `no-fix-version` is a valid workaround but still not optimal. The preferred approach would be to ensure that packages build well with the default options.

Anyway, I checked more and in this particular case the test is failing just because the package was updated to a "much newer" version and the failure will not happen during regular changes after this particular PR is merged and tagged, so LGTM.

2022-03-16 17:03 UTC, Thaodan commented
> > > > Also %check failed at "FAIL: reproducers" (after I had installed libtool to target snapshot).
> > > 
> > > 
> > > That's because the package version isn't matching without tag (check log).
> > 
> > 
> > Ah, okay. So, what I actually needed is `-c no-fix-version`. +1
> 
> From a brief check I would expect that this is addressed by
> 
> https://github.com/sailfishos/libtasn1/blob/e439b365467a923441b190bb1fa3f0bfafb5d1b2/rpm/libtasn1.spec#L65
> - maybe something more could be done here.

This to avoid making the package/gnulib using the inbuild mechanism  to detect the version based on git.

If mb2 resets the version based on the last tags its to bold for the check as noticed by @martyone  above.

2022-03-16 17:05 UTC, merged